### PR TITLE
Issue 1

### PR DESCRIPTION
**Pull request by karankc23**
Issue: 1

#### Short description of what this resolves:
ran all the commands in linux and included django-RESTframework in the project  

#### Changes proposed in this pull request and/or Screenshots of changes:
image of local host 
karankc23 local host

-
-
-

### CODE REVIEW

**Comment by pankaj1707k** [comment]
@karankc23 You haven't included the django-rest-framework in your project. You were not supposed to add the virtual environment in the repo. You can create the virtual environment anywhere in your file system but not inside the repo.

**Comment by garvitchittora** [comment]
> @karankc23 You haven't included the django-rest-framework in your project. You were not supposed to add the virtual environment in the repo. You can create the virtual environment anywhere in your file system but not inside the repo.

better put `env` in gitignore.

**Comment by karankc23** [comment]
@pankaj1707k sir please give me some additional time, so that i can act on it properly

**Comment by pankaj1707k** [comment]
@karankc23 Your time of 2 days was up, so I had to reassign the issue to someone else. Better try next time :)

**Pull request closed without merging**
